name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_DIR: ./codebase/rdicidr-0.1.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.APP_DIR }}

      - name: Run Linter (ESLint)
        run: npm run lint
        working-directory: ${{ env.APP_DIR }}

      - name: Run Formatter (Prettier)
        run: npm run prettier -- --write
        working-directory: ${{ env.APP_DIR }}

      - name: Run Build
        run: npm run build
        working-directory: ${{ env.APP_DIR }}
